version: '1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: ORACLE
      DB_ADDR: oracle
      DB_PORT: 1521
      DB_DATABASE: XE
      DB_USER: SYSTEM
      DB_PASSWORD: oracle
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    volumes:
      # The host directory should contain the `ojdbc.jar` file.
      - ./jdbc:/opt/jboss/keycloak/modules/system/layers/base/com/oracle/jdbc/main/driver
    depends_on:
      - oracle
